services:
  mongo:
    image: mongo:7
    container_name: cham-xanh-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - cham-xanh-mongo-data:/data/db

volumes:
  cham-xanh-mongo-data:
